services:
  
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
      
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9095:9090"
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.1.4
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards:ro
  pact-broker-db:
    image: postgres:16
    container_name: pact-broker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pact_broker
      POSTGRES_USER: pact_broker
      POSTGRES_PASSWORD: pact_broker
    ports:
      - "5433:5432"
    volumes:
      - pact-broker-db-data:/var/lib/postgresql/data
    networks:
      - pact-network

  pact-broker:
    image: pactfoundation/pact-broker:latest
    container_name: pact-broker
    restart: unless-stopped
    depends_on:
      - pact-broker-db
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_HOST: pact-broker-db
      PACT_BROKER_DATABASE_PORT: 5432
      PACT_BROKER_DATABASE_NAME: pact_broker
      PACT_BROKER_DATABASE_USERNAME: pact_broker
      PACT_BROKER_DATABASE_PASSWORD: pact_broker

      # Нужно, чтобы Pact Broker корректно формировал ссылки
      PACT_BROKER_BASE_URL: http://localhost:9292

      # Для docker-compose, чтобы broker подождал Postgres
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "10"

    networks:
      - pact-network

volumes:
  pact-broker-db-data:
  grafana-data:

networks:
  pact-network:
    driver: bridge
