spring.application.name=rate-printer
spring.profiles.default=dev
app.version=${APP_VERSION:0.0.1-SNAPSHOT}

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=30s

spring.cloud.zookeeper.discovery.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
