spring.application.name=rate-printer
server.port=8080

# spring.grpc.client.channels.currency-rate-provider.address=static://localhost:9090

spring.cloud.zookeeper.connect-string=localhost:2181
spring.cloud.zookeeper.discovery.enabled=true


# zookeeper.connect-string=localhost:2181
# zookeeper.service-path=/services/currency-rate-provider
# spring.cloud.zookeeper.discovery.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
