server.port=${HTTP_PORT:8080}

zookeeper.connect-string=${ZOOKEEPER_CONNECT_STRING:localhost:2181}
zookeeper.service-path=${ZOOKEEPER_SERVICE_PATH:/services}
spring.cloud.zookeeper.connect-string=${ZOOKEEPER_CONNECT_STRING:localhost:2181}
