server.port=${HTTP_PORT:8081}
spring.grpc.server.port=${GRPC_PORT:9090}

zookeeper.connect-string=${ZOOKEEPER_CONNECT_STRING:localhost:2181}
zookeeper.service-path=${ZOOKEEPER_SERVICE_PATH:/services}
