spring.application.name=currency-rate-provider
app.version=0.0.1-SNAPSHOT
server.port=8081

spring.grpc.server.port=9090

zookeeper.connect-string=localhost:2181
zookeeper.service-path=/services

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
