spring.application.name=currency-rate-provider
spring.profiles.default=dev
app.version=${APP_VERSION:0.0.1-SNAPSHOT}
spring.grpc.server.shutdown-grace-period=30s

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
